/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unknownpotato.cyfighter.editor.ui;

import com.unknownpotato.cyfighter.editor.Observer;
import com.unknownpotato.cyfighter.editor.controller.Editor;
import com.unknownpotato.cyfighter.editor.controller.tools.SelectionTool;
import com.unknownpotato.cyfighter.editor.model.Entity;
import com.unknownpotato.cyfighter.editor.model.Vector2;

/**
 *
 * @author mikko
 */
public class SelectionToolPanel extends javax.swing.JPanel implements Observer {

    private Window window;
    private SelectionTool selectionTool;

    /**
     * Creates new form SelectPanel
     */
    public SelectionToolPanel() {
        this(null, null);
    }

    public SelectionToolPanel(Window window, SelectionTool selectionTool) {
        this.window = window;
        this.selectionTool = selectionTool;
        this.selectionTool.setObserver(this);
        initComponents();
    }

    public void refresh() {
        updateTypeField();
        updateSelectedLabel();
    }

    private void updateTypeField() {
        if (typeField.hasFocus()) {
            return;
        }
        if (selectionTool.getSelectedEntities().isEmpty()) {
            typeField.setText("");
            typeField.setEnabled(false);
            return;
        }
        if (selectionTool.getSelectedEntities().size() == 1) {
            typeField.setText(selectionTool.getSelectedEntities().get(0).getType());
            typeField.setEnabled(true);
            return;
        }
        typeField.setText("");
        typeField.setEnabled(true);
    }

    private void updateSelectedLabel() {
        if (selectionTool.getSelectedEntities().isEmpty()) {
            selectedLabel.setVisible(false);
            return;
        }

        if (selectionTool.getSelectedEntities().size() == 1) {
            selectedLabel.setVisible(true);
            Entity e = selectionTool.getSelectedEntities().get(0);
            selectedLabel.setText(e.getType() + ": (" + e.getPos().x + ", " + e.getPos().y + ")");
            return;
        }

        if (selectionTool.getSelectedEntities().size() > 1) {
            selectedLabel.setVisible(true);
            selectedLabel.setText(selectionTool.getSelectedEntities().size() + " selected");
        } else {
            selectedLabel.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteButton = new javax.swing.JButton();
        selectedLabel = new javax.swing.JLabel();
        typeField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        selectedLabel.setText("Lorem ipsum");

        typeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                typeFieldFocusLost(evt);
            }
        });
        typeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                typeFieldKeyTyped(evt);
            }
        });

        jLabel2.setText("Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeField))
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteButton)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(selectedLabel)
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        this.selectionTool.delete();
        window.refresh();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void typeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typeFieldFocusLost
        this.selectionTool.changeTypeOfSelectedEntities(typeField.getText());
        this.refresh();
    }//GEN-LAST:event_typeFieldFocusLost

    private void typeFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeFieldKeyTyped
        //System.out.println(typeField.getText());
        this.selectionTool.changeTypeOfSelectedEntities(typeField.getText());
        this.refresh();
    }//GEN-LAST:event_typeFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel selectedLabel;
    private javax.swing.JTextField typeField;
    // End of variables declaration//GEN-END:variables
}
